# Generated by Django 5.1.7 on 2025-04-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_contentmanager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_moderator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
