# Generated by Django 5.1.7 on 2025-04-08 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_assigned_contentmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_contentmanager',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_communitymanagers',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_community_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
