# Generated by Django 4.2.25 on 2025-11-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OptimalPostingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("hour", models.IntegerField()),
                (
                    "engagement_score",
                    models.FloatField(
                        help_text="Engagement score for this time (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-engagement_score"],
                "unique_together": {("platform", "day_of_week", "hour")},
            },
        ),
        migrations.CreateModel(
            name="HashtagPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hashtag",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("fitness", "Fitness 💪"),
                            ("fashion", "Fashion 👗"),
                            ("tech", "Technology 💻"),
                            ("food", "Food & Beverage 🍕"),
                            ("travel", "Travel ✈️"),
                            ("lifestyle", "Lifestyle 🌟"),
                            ("business", "Business 💼"),
                            ("marketing", "Marketing 📊"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                        ],
                        default="instagram",
                        max_length=20,
                    ),
                ),
                (
                    "avg_engagement_rate",
                    models.FloatField(help_text="Average engagement rate (0-100%)"),
                ),
                (
                    "usage_frequency",
                    models.IntegerField(
                        default=0, help_text="Times used in sample data"
                    ),
                ),
                (
                    "reach_estimate",
                    models.IntegerField(
                        default=0, help_text="Estimated reach (synthetic)"
                    ),
                ),
                ("trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-avg_engagement_rate", "-usage_frequency"],
                "indexes": [
                    models.Index(
                        fields=["industry", "platform"],
                        name="ai_integrat_industr_310fff_idx",
                    ),
                    models.Index(
                        fields=["avg_engagement_rate"],
                        name="ai_integrat_avg_eng_6df904_idx",
                    ),
                ],
            },
        ),
    ]
