# Generated by Django 4.2.25 on 2025-11-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_post_is_moderator_rejected_and_more"),
        ("ai_integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Model version identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        help_text="Type of model (e.g., RandomForest, LinearRegression)",
                        max_length=50,
                    ),
                ),
                (
                    "training_samples",
                    models.IntegerField(
                        help_text="Number of samples used for training"
                    ),
                ),
                ("r2_score", models.FloatField(help_text="R² score on training data")),
                ("mae", models.FloatField(help_text="Mean Absolute Error")),
                ("rmse", models.FloatField(help_text="Root Mean Squared Error")),
                (
                    "training_data_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("real", "Real"),
                            ("combined", "Combined"),
                        ],
                        default="synthetic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this model version is actively used for predictions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption_length", models.IntegerField()),
                ("hashtag_count", models.IntegerField()),
                ("time_of_day", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("platform", models.CharField(max_length=20)),
                ("media_type", models.CharField(max_length=20)),
                ("brand_sentiment", models.FloatField()),
                (
                    "engagement_score",
                    models.FloatField(help_text="Target engagement score (0-100)"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("real", "Real"),
                            ("combined", "Combined"),
                        ],
                        default="synthetic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Training Data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EngagementForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption_length",
                    models.IntegerField(
                        help_text="Length of the post caption in characters"
                    ),
                ),
                (
                    "hashtag_count",
                    models.IntegerField(help_text="Number of hashtags in the post"),
                ),
                (
                    "time_of_day",
                    models.IntegerField(
                        help_text="Hour of day when post is scheduled (0-23)"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        help_text="Day of week when post is scheduled (0=Monday, 6=Sunday)"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("carousel", "Carousel"),
                            ("text", "Text Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "brand_sentiment",
                    models.FloatField(
                        default=0.5,
                        help_text="Sentiment score of the post content (0-1)",
                    ),
                ),
                (
                    "predicted_engagement_score",
                    models.FloatField(help_text="Predicted engagement score (0-100)"),
                ),
                (
                    "engagement_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Engagement level category",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Model confidence in prediction (0-1)"),
                ),
                (
                    "actual_engagement_score",
                    models.FloatField(
                        blank=True,
                        help_text="Actual engagement after publishing",
                        null=True,
                    ),
                ),
                (
                    "actual_engagement_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Actual engagement level after publishing",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "predicted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the prediction was made"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        help_text="The post for which engagement is being forecasted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_forecast",
                        to="content.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Engagement Forecasts",
                "ordering": ["-predicted_at"],
            },
        ),
    ]
