# Generated by Django 4.2 on 2025-07-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="Feedback provided when approving or rejecting the post",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="feedback_at",
            field=models.DateTimeField(
                blank=True, help_text="When the feedback was provided", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="feedback_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who provided the feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
