# Generated by Django 4.2 on 2025-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_post_feedback_post_feedback_at_post_feedback_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="client_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the client approved this post", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="client_rejected_at",
            field=models.DateTimeField(
                blank=True, help_text="When the client rejected this post", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_client_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the client has approved this post (independent of status)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_moderator_rejected",
            field=models.BooleanField(
                default=False, help_text="Whether the moderator has rejected this post"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderator_rejected_at",
            field=models.DateTimeField(
                blank=True, help_text="When the moderator rejected this post", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderator_validated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the moderator validated this post",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When the post was actually published", null=True
            ),
        ),
    ]
