# Generated by Django 4.2 on 2025-08-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_post_client_approved_at_post_client_rejected_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_moderator_rejected",
        ),
        migrations.AddField(
            model_name="post",
            name="is_moderator_validated",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the moderator has validated this post",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_client_approved",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the client has approved this post (independent of status)",
                null=True,
            ),
        ),
    ]
