# Generated by Django 4.2.25 on 2025-11-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_post_is_moderator_rejected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(default=0, help_text="Total likes/reactions"),
                ),
                (
                    "comments",
                    models.IntegerField(default=0, help_text="Total comments"),
                ),
                (
                    "shares",
                    models.IntegerField(default=0, help_text="Total shares/retweets"),
                ),
                (
                    "reach",
                    models.IntegerField(
                        default=0, help_text="Unique users who saw the post"
                    ),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        default=0, help_text="Total times the post was displayed"
                    ),
                ),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Engagement rate percentage (engagement/reach * 100)",
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        default=0, help_text="Total clicks on post links"
                    ),
                ),
                (
                    "video_views",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Video views (if post contains video)",
                        null=True,
                    ),
                ),
                (
                    "video_watch_time",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Total watch time in seconds",
                        null=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time analytics were synced from platform",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        help_text="The post these analytics belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="content.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Analytics",
                "verbose_name_plural": "Post Analytics",
                "ordering": ["-last_synced_at"],
                "indexes": [
                    models.Index(
                        fields=["post"], name="content_pos_post_id_b6ab1d_idx"
                    ),
                    models.Index(
                        fields=["-last_synced_at"],
                        name="content_pos_last_sy_1a8478_idx",
                    ),
                ],
            },
        ),
    ]
