# Generated by Django 5.1.7 on 2025-03-14 19:34

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')  
    User.objects.create(
        email='test@example.com',
        password=make_password('testpassword123'),  
        is_verified=True, 
        is_administrator=True,  
        is_moderator=False,  
        is_community_manager=False,  
        is_client=False,  
    )

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(create_default_user), 
    ]