name: CI/CD Pipeline for Django and Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python for Django
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install Django backend dependencies
      - name: Install backend dependencies (Django)
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Django tests
      - name: Run Django tests
        run: |
          cd backend
          python manage.py test

      # Step 5: Set up Node.js for Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 6: Install Next.js frontend dependencies
      - name: Install frontend dependencies (Next.js)
        run: |
          cd frontend
          npm install

      # Step 7: Build frontend (Next.js)
      - name: Build frontend (Next.js)
        run: |
          cd frontend
          npm run build

      # Step 8: Optional - Deploy backend to Heroku or AWS (example)
      # Replace this step with your own deployment process.
      - name: Deploy backend to Heroku (optional)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Ensure you configure your Heroku secret
        run: |
          git remote add heroku https://git.heroku.com/your-app.git
          git push heroku main

      # Step 9: Optional - Deploy frontend to Vercel (example)
      # Replace this step with your own deployment process.
      - name: Deploy Next.js frontend to Vercel (optional)
        run: |
          cd frontend
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Replace with your deployment method
          
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Deploy Django backend to your hosting service (e.g., Heroku, AWS)
      - name: Deploy backend to Heroku (optional)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Ensure secret is set
        run: |
          git remote add heroku https://git.heroku.com/your-app.git
          git push heroku main
