name: CI/CD Pipeline  Next.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
     
      # Step 5: Set up Node.js for Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 6: Install Next.js frontend dependencies
      - name: Install frontend dependencies (Next.js)
        run: |
          cd frontend
          npm install

      # Step 7: Build frontend (Next.js)
      - name: Build frontend (Next.js)
        run: |
          cd frontend
          npm run build
          
 